# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-25 12:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jagdreisencheck.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Answer')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Posted')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Date Posted')),
                ('answers', models.ManyToManyField(to='faq.FaqAnswer', verbose_name='Answers')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='FaqInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='FAQ Title')),
                ('tags', jagdreisencheck.custom_fields.ListField(blank=True, null=True, verbose_name='Tags')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Posted')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Date Posted')),
                ('model', models.CharField(max_length=50, verbose_name='Associated Model')),
                ('identifier', models.CharField(max_length=50, verbose_name='Instance ID')),
                ('highlighted', models.BooleanField(default=False, verbose_name='Highlighted')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified by the owner')),
                ('answers', models.ManyToManyField(to='faq.FaqAnswer', verbose_name='Answers')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
