# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqinstance',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Question Title'),
        ),
    ]
