# Generated by Django 2.1.9 on 2019-06-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20190307_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqanswer',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='faqinstance',
            name='answers',
        ),
        migrations.AddField(
            model_name='faqanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faq.FaqInstance', verbose_name='Question'),
        ),
    ]
