# Generated by Django 2.1.7 on 2019-04-05 11:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0039_auto_20190402_1928'),
        ('travelling', '0053_auto_20190404_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='HunterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('budget', djmoney.models.fields.MoneyField(decimal_places=2, default=None, default_currency='EUR', max_digits=8, null=True, verbose_name='Budget')),
                ('license_since', models.IntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950), (1949, 1949), (1948, 1948), (1947, 1947), (1946, 1946), (1945, 1945), (1944, 1944), (1943, 1943), (1942, 1942), (1941, 1941), (1940, 1940), (1939, 1939), (1938, 1938), (1937, 1937), (1936, 1936), (1935, 1935), (1934, 1934), (1933, 1933), (1932, 1932), (1931, 1931), (1930, 1930), (1929, 1929), (1928, 1928), (1927, 1927), (1926, 1926), (1925, 1925), (1924, 1924), (1923, 1923), (1922, 1922), (1921, 1921), (1920, 1920)], null=True, verbose_name='Year the hunting license was obtained')),
                ('shooting_experience', models.IntegerField(null=True, verbose_name='Max. Shooting distance')),
                ('physical_fitness', models.IntegerField(choices=[(1, 'No fitness'), (2, 'Almost no fitness'), (3, 'Some fitness'), (4, 'Good fitness'), (5, 'Strong fitness')], null=True, verbose_name='Physical Fitness')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelling.Game', verbose_name='Primary Game to hunt')),
            ],
        ),
        migrations.CreateModel(
            name='TripInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=35, null=True, verbose_name='Phone')),
                ('num_of_non_hunters', models.IntegerField(blank=True, null=True, verbose_name='Number of accompanying Persons')),
                ('hunting_type', models.CharField(choices=[('P', 'Stalking'), ('A', 'Stand Hunting'), ('G', 'Joint Hunting')], default='P', max_length=1, verbose_name='Primary Hunting Type')),
                ('accommodation', models.CharField(choices=[('SO', 'Self Organized'), ('CA', 'Camping'), ('CO', 'Simple Cottage'), ('HH', 'Holiday Home / Hunting Chalet'), ('LO', 'Lodge'), ('HC', 'Hunting Chalet'), ('HO', 'Hotel')], max_length=2, null=True, verbose_name='Accommodation')),
                ('time_start', models.DateField(error_messages={'invalid': 'Please provide a valid date. Format: dd.mm.yyyy'}, null=True, verbose_name='When would you like to start the trip?')),
                ('time_end', models.DateField(error_messages={'invalid': 'Please provide a valid date. Format: dd.mm.yyyy'}, null=True, verbose_name='When would you like to end the trip?')),
                ('inquiry', ckeditor.fields.RichTextField(null=True, verbose_name='Further Details, Wishes & Questions')),
                ('consent_to_be_contacted', models.BooleanField(default=False, verbose_name='Consent to be contacted')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date of Inquiry')),
                ('traveller_status', models.CharField(choices=[('OP', 'Open'), ('FC', 'First contact'), ('OS', 'Offer sent'), ('FU', 'Follow up required'), ('OA', 'Offer accepted'), ('PR', 'Payment received'), ('CT', 'Customer on trip'), ('CT', 'Customer returned'), ('IR', 'Customer invited for review'), ('RR', 'Review received'), ('CL', 'Closed')], default='OP', max_length=2, verbose_name='Travel Status')),
                ('read', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Inquiry has been opened')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelling.Trip', verbose_name='Associated Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.IndividualProfile', verbose_name='Inquiring User')),
            ],
        ),
        migrations.AddField(
            model_name='hunterdata',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiries.TripInquiry', verbose_name='Associated Inquiry'),
        ),
    ]
