# Generated by Django 2.1.7 on 2019-04-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunterdata',
            name='name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Name'),
        ),
    ]
