# Generated by Django 2.1.7 on 2019-04-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0053_auto_20190404_1857'),
        ('inquiries', '0002_hunterdata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunterdata',
            name='game',
        ),
        migrations.AddField(
            model_name='hunterdata',
            name='game',
            field=models.ManyToManyField(null=True, to='travelling.Game', verbose_name='Primary Game to hunt'),
        ),
    ]
