# Generated by Django 2.1.7 on 2019-04-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_auto_20190406_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunterdata',
            name='game',
            field=models.ManyToManyField(to='travelling.Game', verbose_name='Primary Game to hunt'),
        ),
    ]
