# Generated by Django 2.1.7 on 2019-04-07 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_auto_20190406_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripinquiry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tripinquiry',
            name='name',
        ),
    ]
