# Generated by Django 2.1.7 on 2019-04-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_auto_20190407_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='tripinquiry',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
    ]
