# Generated by Django 2.1.7 on 2019-04-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0007_auto_20190407_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripinquiry',
            name='iq',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Inquiry ID'),
        ),
    ]
