# Generated by Django 2.1.8 on 2019-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0008_tripinquiry_iq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunterdata',
            name='physical_fitness',
            field=models.IntegerField(choices=[(1, 'less than 1km walking distance per day'), (2, 'between 1km and up to 2.5km walking distance per day'), (3, 'between 2.5km and up to 5km walking distance per day'), (4, 'between 5km and up to 10km walking distance per day'), (5, 'more than 10km walking distance per day')], null=True, verbose_name='Physical Fitness'),
        ),
    ]
