# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-02 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import jagdreisencheck.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyaltyElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Title')),
                ('file', models.FileField(upload_to='loyalty/', verbose_name='Associated File')),
                ('corporate', models.BooleanField(default=False, verbose_name='For corporate users')),
                ('user_passes_test', jagdreisencheck.custom_fields.ListField(blank=True, null=True, verbose_name='Tests that the user has to pass')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Title')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField()),
                ('subscribers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Subscribers')),
            ],
        ),
    ]
