# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-03 19:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mailing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyaltyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.RemoveField(
            model_name='customerloyaltyelement',
            name='user_passes_test',
        ),
        migrations.AlterField(
            model_name='customerloyaltyelement',
            name='file',
            field=models.FileField(upload_to='loyalty/', validators=[mailing.models.validate_pdf], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='customerloyaltyelement',
            name='name',
            field=models.CharField(editable=False, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='customerloyaltycheck',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.CustomerLoyaltyElement', verbose_name='Associated File'),
        ),
        migrations.AddField(
            model_name='customerloyaltycheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
