# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import mailing.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20190303_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloyaltyelement',
            name='file',
            field=models.FileField(null=True, upload_to='loyalty/', validators=[mailing.models.validate_pdf], verbose_name='File'),
        ),
    ]
