# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_auto_20190303_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloyaltyelement',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
