# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_auto_20190303_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerloyaltyelement',
            options={'verbose_name': 'Customer Loyalty Element', 'verbose_name_plural': 'Customer Loyalty Elements'},
        ),
        migrations.AddField(
            model_name='customerloyaltyelement',
            name='description',
            field=models.TextField(null=True, verbose_name='Text to display on the user page'),
        ),
    ]
