# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-03 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_auto_20190303_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloyaltyelement',
            name='link_description',
            field=models.CharField(max_length=150, null=True, verbose_name='Link description'),
        ),
    ]
