# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-03 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_customerloyaltyelement_link_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerloyaltyelement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Text to display on the user page'),
        ),
    ]
