# Generated by Django 2.1.7 on 2019-03-13 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0007_auto_20190303_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mail/attachments/', verbose_name='Attachment File')),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Mail Title')),
                ('body', models.TextField(verbose_name='Mail Body')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.MailingList', verbose_name='Mailing List')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.Mail', verbose_name='E-Mail'),
        ),
    ]
