# Generated by Django 2.1.7 on 2019-03-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_auto_20190313_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Mail Sent'),
        ),
    ]
