# Generated by Django 2.1.7 on 2019-03-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='variant',
            field=models.CharField(choices=[('MAS', 'Send Bulk E-Mail'), ('IND', 'Send E-Mails Individually')], default='MAS', max_length=3, verbose_name='E-Mail Variant'),
        ),
    ]
