import os

from django.utils.translation import gettext_lazy as _

gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'jagdreisencheck', 'static')]


"""
Django settings for jagdreisencheck project.

Generated by 'django-admin startproject' using Django 1.11.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

DEBUG = eval(os.environ['DEBUG'])

TESTSYSTEM = eval(os.environ['TESTSYSTEM'])
SITE_ID = eval(os.environ['SITE_ID'])
SECRET_KEY = str(os.environ['SECRET_KEY'])
REG_KEY = bytes(os.environ['REG_KEY'], encoding='UTF-8')
ROOT_URLCONF = 'jagdreisencheck.urls'
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = '/accounts/login/'

ADMINS = eval(os.environ['ADMINS'])
SERVER_EMAIL = os.environ['SERVER_EMAIL']
ALLOWED_HOSTS = eval(os.environ['ALLOWED_HOSTS'])
CONTENT_TYPES = eval(os.environ['CONTENT_TYPES'])
MAX_UPLOAD_SIZE = int(os.environ['MAX_UPLOAD_SIZE'])
PAGINATOR_NUMBER = 6

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
# SESSION_COOKIE_NAME = 'JAGDREISENCHECK'
SECURE_HSTS_SECONDS = 15768000
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_FRAME_DENY = True
SESSION_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = 'Lax'
SECURE_BROWSER_XSS_FILTER = True
SESSION_COOKIE_SECURE = not DEBUG
# SESSION_COOKIE_SAMESITE = os.environ['SESSION_COOKIE_SAMESITE']

CMS_PERMISSION = True
CMS_TOOLBAR_ANONYMOUS_ON = False

# SOURCE & GUIDELINE: https://github.com/ottoyiu/django-cors-headers/
CORS_ORIGIN_ALLOW_ALL = eval(os.environ['CORS_ORIGIN_ALLOW_ALL'])
CORS_ORIGIN_WHITELIST = eval(os.environ['CORS_ORIGIN_WHITELIST'])
CORS_ALLOW_HEADERS = os.environ['CORS_ALLOW_HEADERS']
CORS_ALLOW_CREDENTIALS = eval(os.environ['CORS_ALLOW_CREDENTIALS'])
CSRF_TRUSTED_ORIGINS = eval(os.environ['CSRF_TRUSTED_ORIGINS'])

# Source: https://django-csp.readthedocs.io/
# CSP_DEFAULT_SRC = ["'self'", "wss://ws7.hotjar.com/", "https://in.hotjar.com/", "https://sentry.hotjar.com",
#                    "jagdreisencheck.s3.amazonaws.com", "www.google-analytics.com"]
# CSP_SCRIPT_SRC = ["'self'", "'unsafe-inline'", "jagdreisencheck.s3.amazonaws.com", "www.googletagmanager.com",
#                   "www.google-analytics.com", "static.hotjar.com", "maps.googleapis.com", "code.jquery.com",
#                   "unpkg.com", "www.google.com", ]
# CSP_INCLUDE_NONCE_IN = ('script-src',)
# CSP_IMG_SRC = ["'self'", "'unsafe-inline'"]
# CSP_OBJECT_SRC = ["'self'"]
# CSP_FRAME_SRC = ["'self'", "www.google.com", "stats.g.doubleclick.net", "vars.hotjar.com",
#                  "jagdreisencheck.s3.amazonaws.com"]
# CSP_FONT_SRC = ["'self'", "jagdreisencheck.s3.amazonaws.com", "stackpath.bootstrapcdn.com", "fonts.gstatic.com",
# "jagdreisencheck.s3.amazonaws.com"]
# CSP_STYLE_SRC = ["'self'", "'unsafe-inline'", "stackpath.bootstrapcdn.com", "code.jquery.com", "fonts.googleapis.com",
# "jagdreisencheck.s3.amazonaws.com"]


# LOCALIZATION SETTINGS
LANGUAGE_CODE = 'de'
TIME_ZONE = 'Europe/Berlin'
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [('de', gettext('de')), ('en', gettext('en'))]
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
    os.path.join(BASE_DIR, 'jet', 'locale'),
    os.path.join(BASE_DIR, 'jet', 'dashboard', 'locale'),
]
CMS_LANGUAGES = {
    1: [
        {
            'code': 'de',
            'name': gettext('de'),
            'redirect_on_fallback': True,
            'fallbacks': ['en'],
            'public': True,
            'hide_untranslated': False,
        },
        {
            'code': 'en',
            'name': gettext('en'),
            'redirect_on_fallback': False,
            'fallbacks': ['de'],
            'public': False,
            'hide_untranslated': True,
        },
    ],
    'default': {
        'fallbacks': ['de'],
        'redirect_on_fallback': True,
        'public': True,
        'hide_untranslated': False,
    },
}
PARLER_LANGUAGES = {
    1: [{'code': 'de', }],
    'default': {
        'fallback': 'de',  # defaults to PARLER_DEFAULT_LANGUAGE_CODE
        'hide_untranslated': False,  # the default; let .active_translations() return fallbacks too.
    }
}


# AWS STORAGE CONFIG
STATIC_URL = os.environ['STATIC_URL']
MEDIA_URL = os.environ['MEDIA_URL']
CMS_MEDIA_PATH = os.environ['CMS_MEDIA_PATH']

MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')


if not DEBUG:
    AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
    AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
    AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
    AWS_S3_CUSTOM_DOMAIN = os.environ['AWS_S3_CUSTOM_DOMAIN']
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
    # AWS_LOCATION = os.environ['AWS_LOCATION']
    AWS_IS_GZIPPED = True
    DEFAULT_FILE_STORAGE = os.environ['DEFAULT_FILE_STORAGE']
    STATICFILES_STORAGE = os.environ['STATICFILES_STORAGE']
    
    
# LOGGER CONFIG
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        'django.security.DisallowedHost': {
            'handlers': ['null'],
            'propagate': False,
        },
    },
}


# TEMPLATE CONFIG
TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [
        os.path.join(BASE_DIR, 'jagdreisencheck', 'templates'),
        os.path.join(BASE_DIR, 'accounts', 'templates'),
        os.path.join(BASE_DIR, 'travelling', 'templates'),
        # os.path.join(BASE_DIR, 'analytics', 'templates')
    ],
    'OPTIONS': {
        'context_processors': [
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
            'django.template.context_processors.i18n',
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.template.context_processors.media',
            'django.template.context_processors.csrf',
            'django.template.context_processors.tz',
            'sekizai.context_processors.sekizai',
            'django.template.context_processors.static',
            'cms.context_processors.cms_settings',
            'django_settings_export.settings_export',
            'jagdreisencheck.context_processors.testsystem',
        ],
        'loaders': [
            'app_namespace.Loader',
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader'
        ],
    },
}]
CMS_TEMPLATES_DIR = os.path.join(BASE_DIR, "jagdreisencheck", "templates", "cms_pages")
CMS_TEMPLATE_INHERITANCE = True


# MIDDLEWARE CONFIG
MIDDLEWARE = (
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # 'django_cookies_samesite.middleware.CookiesSameSite',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    # 'csp.middleware.CSPMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
)

if TESTSYSTEM:
    MIDDLEWARE += (
        'jagdreisencheck.middelware.authentication.RequireLoginMiddleware',
    )
    
    
# INSTALLED EXTENSIONS
INSTALLED_APPS = (
    # Core Django Applications.
    'accounts',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'jet',
    'jet.dashboard',
    'django.contrib.admin',
    'adminsortable2',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'django.contrib.flatpages',
    'django_comments',
    'django_countries',
    'django_languages',
    'django_user_agents',
    'djmoney',
    
    # Django CMS extensions
    'cms',
    'menus',
    'aldryn_apphooks_config',
    'aldryn_apphook_reload',
    'sekizai',
    'treebeard',
    'filer',
    'djangocms_file',
    'djangocms_picture',
    'djangocms_style',
    'djangocms_snippet',
    'djangocms_video',
    'djangocms_column',
    'djangocms_text_ckeditor',
    'djangocms_blog',
    
    # Alphabetically sorted packages.
    'analytical',
    'anymail',
    'collectfast',
    'corsheaders',
    'django_cron',
    'django_google_maps',
    'django_settings_export',
    'django_ses',
    'easy_thumbnails',
    'image_optimizer',
    'import_export',
    'mathfilters',
    'meta',
    'mptt',
    'newsletter',
    'parler',
    'psycopg2',
    'rest_framework',
    'robots',
    'sorl.thumbnail',
    'sortedm2m',
    'storages',
    'tagging',
    'taggit',
    'taggit_autosuggest',
    
    # Breadcrumbs TODO: Maybe replace this package with a more advanced one.
    'url_breadcrumbs',
    
    # Custom Applications
    'cms_plugin_directory',
    'cmsplugin_filer_image',
    'faq',
    'inquiries',
    'jagdreisencheck',
    'jagdreisencheck.management',
    'languages',
    'mailing',
    'podcasting',
    'pricing',
    'recaptcha3',
    'search',
    'seotools',
    'slideshow',
    'travelling',
)


# DATABASE CONFIG
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
        "LOCATION": "127.0.0.1:11211"
    }
}

if DEBUG:
    DATABASES = {
        'default': {
            'CONN_MAX_AGE': 0,
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'HOST': 'localhost',
            'NAME': 'postgres',
            'PASSWORD': 'jr2018!',
            'PORT': '5455',
            'USER': 'postgres'
        }
    }
else:
    DATABASES = {
        'default': {
            'CONN_MAX_AGE': 0,
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'HOST': os.environ['RDS_HOSTNAME'],
            'NAME': os.environ['RDS_DB_NAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'PORT': os.environ['RDS_PORT'],
            'USER': os.environ['RDS_USERNAME']
        }
    }
    
    
# META CONFIG
META_SITE_PROTOCOL = 'https'
META_USE_SITES = True


# SETTINGS EXPORT
SETTINGS_EXPORT = []

INTERNAL_IPS = (
    '127.0.0.1',
    'localhost',
)

############## Django Money Configuration ##############
CURRENCIES = ('USD', 'EUR')
CURRENCY_CHOICES = [('USD', 'USD $'), ('EUR', 'EUR €')]

############## Newsletter Configuration ##############
NEWSLETTER_CONFIRM_EMAIL = os.environ['NEWSLETTER_CONFIRM_EMAIL']  # Necessary, GDPR
NEWSLETTER_RICHTEXT_WIDGET = 'ckeditor.widgets.CKEditorWidget'

NEWSLETTER_EMAIL_DELAY = 1  # Second
NEWSLETTER_BATCH_DELAY = 120  # Seconds
NEWSLETTER_BATCH_SIZE = 250

NEWSLETTER_CONFIRM_EMAIL_SUBSCRIBE = True
NEWSLETTER_CONFIRM_EMAIL_UNSUBSCRIBE = False
NEWSLETTER_CONFIRM_EMAIL_UPDATE = False

############## Email Config ##############
EMAIL_BACKEND = 'django_ses.SESBackend'
AWS_SES_REGION_NAME = 'eu-west-1'
AWS_SES_REGION_ENDPOINT = 'email.eu-west-1.amazonaws.com'
# EMAIL_HOST = environment['email']['host']
# EMAIL_HOST_USER = environment['email']['user']
# EMAIL_HOST_PASSWORD = environment['email']['host-password']
# EMAIL_PORT = environment['email']['port']
EMAIL_USE_TLS = True
FROM_EMAIL = os.environ['FROM_EMAIL']

################ GOOGLE ACCOUNTS ####################
# Tool: https://django-analytical.readthedocs.io/en/latest/
# CLICKY_SITE_ID = '101145485'
GOOGLE_ANALYTICS_PROPERTY_ID = os.environ['GOOGLE_ANALYTICS_PROPERTY_ID']
GOOGLE_ANALYTICS_TRACKING_STYLE = eval(os.environ['GOOGLE_ANALYTICS_TRACKING_STYLE']) # Track Single Domain Jagdreisencheck.de
GOOGLE_ANALYTICS_DISPLAY_ADVERTISING = eval(os.environ['GOOGLE_ANALYTICS_DISPLAY_ADVERTISING'])  # Collects Demographic Data
GOOGLE_ANALYTICS_SITE_SPEED = eval(os.environ['GOOGLE_ANALYTICS_SITE_SPEED'])  # Page Performance
GOOGLE_ANALYTICS_ANONYMIZE_IP = eval(os.environ['GOOGLE_ANALYTICS_ANONYMIZE_IP'])  # Mandatory in Germany
GOOGLE_ANALYTICS_SAMPLE_RATE = eval(os.environ['GOOGLE_ANALYTICS_SAMPLE_RATE'])
GOOGLE_ANALYTICS_SESSION_COOKIE_TIMEOUT = eval(os.environ['GOOGLE_ANALYTICS_SESSION_COOKIE_TIMEOUT'])
GOOGLE_ANALYTICS_VISITOR_COOKIE_TIMEOUT = eval(os.environ['GOOGLE_ANALYTICS_VISITOR_COOKIE_TIMEOUT'])
GOOGLE_RECAPTCHA_SECRET_KEY = '6LeSO4EUAAAAAHGBStpztG4dJWFNMeNaCsvW5NOo'
GOOGLE_MAPS_API_KEY = 'AIzaSyAjqKAyjSAW7VZL7suTAUC_Kn3gLH-hurY'

################ ADVERTISEMENT ##################
# https://github.com/lethain/django-monetize


#####################################################
#                 IMAGE OPTIMIZER                   #
#####################################################
OPTIMIZED_IMAGE_METHOD = 'pillow'
THUMBNAIL_DEBUG = False

if not DEBUG:
    THUMBNAIL_DEFAULT_STORAGE = 'jagdreisencheck.storage_backends.MediaStorage'
    
THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)
DJANGOCMS_VIDEO_TEMPLATES = [
    ('fullscreen/', _('Fullscreen Video')),
]

DJANGOCMS_PICTURE_TEMPLATES = [
    ('background-fullscreen', _('Full Screen Background Image')),
    ('index-bg-fullscreen', _('Full Screen Index Image (100% Width)'))
]

DJANGOCMS_PICTURE_NESTING = True

#####################################################
#                 RECAPTCHA                         #
#####################################################
RECAPTCHA_PRIVATE_KEY = '6Lek9JgUAAAAAHgIn-gwsIufgfgmAbzk3PpIgmSo'
RECAPTCHA_PUBLIC_KEY = '6Lek9JgUAAAAAHck7c8nMPsmrBcFwy35rhoCQZyV'
RECAPTCHA_DEFAULT_ACTION = 'generic'
RECAPTCHA_SCORE_THRESHOLD = 0.4

# #####################################################
#                 ROBOTS TXT                        #
#####################################################
ROBOTS_CACHE_TIMEOUT = 60 * 60 * 24

#####################################################
#                 JET DASHBOARD                     #
#####################################################

# JET_MODULE_GOOGLE_ANALYTICS_CLIENT_SECRETS_FILE = os.path.join(PROJECT_DIR, 'client_secrets.json')
JET_MODULE_GOOGLE_ANALYTICS_CLIENT_SECRETS_FILE = os.path.join(BASE_DIR, 'jagdreisencheck', '.env',
                                                               'analytics-secret.json')
JET_INDEX_DASHBOARD = 'jet.dashboard.dashboard.JagdreisencheckDashboard'

JET_THEMES = [
    {
        'theme': 'jagdreisencheck',  # theme folder name
        'color': '#61b561',  # color of the theme's button in user menu
        'title': 'Jagdreisencheck'  # theme title
    },
    {
        'theme': 'default',
        'color': '#cccccc',
        'title': 'Default'
    },
    {
        'theme': 'green',
        'color': '#44b78b',
        'title': 'Green'
    },
    {
        'theme': 'light-green',
        'color': '#2faa60',
        'title': 'Light Green'
    },
    {
        'theme': 'light-violet',
        'color': '#a464c4',
        'title': 'Light Violet'
    },
    {
        'theme': 'light-blue',
        'color': '#5EADDE',
        'title': 'Light Blue'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light Gray'
    }
]

JET_DEFAULT_THEME = 'jagdreisencheck'
JET_CHANGE_FORM_SIBLING_LINKS = True

JET_SIDE_MENU_ITEMS = [  # A list of application or custom item dicts
    {'label': _('User Management'), 'app_label': 'accounts', 'items': [
        {'name': 'accounts.User', 'label': _('Auth User'),
         'url': {'type': 'model', 'app_label': 'accounts', 'model': 'user'}},
        {'name': 'accounts.IndividualProfile', 'label': _('Hunter Accounts'),
         'url': {'type': 'model', 'app_label': 'accounts', 'model': 'individualprofile'}},
        {'name': 'accounts.CorporateProfile', 'label': _('Corporate Accounts'),
         'url': {'type': 'model', 'app_label': 'accounts', 'model': 'corporateprofile'}},
        {'name': 'accounts.CompanyName', 'label': _('Company Name Instances'),
         'url': {'type': 'model', 'app_label': 'accounts', 'model': 'companyname'}},
        {'name': 'accounts.Group', 'label': _('Groups'),
         'url': {'type': 'model', 'app_label': 'accounts', 'model': 'group'}},
        {'name': 'accounts.Permission', 'label': _('Permissions'),
         'url': {'type': 'model', 'app_label': 'accounts', 'model': 'permission'}},
    ]},
    {'label': _('Travel Management'), 'app_label': 'travelling', 'items': [
        {'name': 'travelling.trip', 'label': _('Trip Management'),
         'url': {'type': 'model', 'app_label': 'travelling', 'model': 'trip'}},
        {'name': 'jet.trip', 'label': _('Trip Moderation'),
         'url': {'type': 'reverse', 'name': 'jet-dashboard:moderate_trips'}},
        {'name': 'travelling.game', 'label': _('Game Management'),
         'url': {'type': 'model', 'app_label': 'travelling', 'model': 'game'}},
        {'name': 'travelling.Rating', 'label': _('Rating Management'),
         'url': {'type': 'model', 'app_label': 'travelling', 'model': 'rating'}},
    ]},
    {'label': _('Blog (Academy)'), 'app_label': 'djangocms_blog', 'items': [
        {'name': 'djangocms_blog.post', 'label': _('Articles'),
         'url': {'type': 'model', 'app_label': 'djangocms_blog', 'model': 'post'}},
        {'name': 'djangocms_blog.category', 'label': _('Categories'),
         'url': {'type': 'model', 'app_label': 'djangocms_blog', 'model': 'blogcategory'}},
        {'name': 'djangocms_blog.blogconfig', 'label': _('Settings'),
         'url': {'type': 'model', 'app_label': 'djangocms_blog', 'model': 'blogconfig'}},
        {'name': 'podcasting.Show', 'label': _('Podcasts'), 'url': {'type': 'app', 'app_label': 'podcasting'}},
    ]},
    {'label': _('SEO'), 'app_label': 'robots', 'items': [
        {'name': 'robots.Rule', 'label': _('Robots.txt Rules'),
         'url': {'type': 'model', 'app_label': 'robots', 'model': 'rule'}},
        {'name': 'seotools.SEOCountryDescriptor', 'label': _('SEO Tools'),
         'url': {'type': 'app', 'app_label': 'seotools'}},
    ]},
    {'label': _('CRM'), 'app_label': 'mailing', 'items': [
        {'name': 'mailing.MailingList', 'label': _('Mailing List Management'),
         'url': {'type': 'model', 'app_label': 'mailing', 'model': 'mailinglist'}},
        {'name': 'jet.WriteEmail', 'label': _('Write an E-Mail to a mailing list'),
         'url': {'type': 'reverse', 'name': 'jet-dashboard:write_mail'}},
        {'name': 'django_ses.Dashboard', 'label': _('Mailing Statistics'),
         'url': {'type': 'reverse', 'name': 'django_ses_stats'}},
        {'name': 'seotools.SEOCountryDescriptor', 'label': _('Registration Intro'),
         'url': {'type': 'model', 'app_label': 'seotools', 'model': 'registrationinfographic'}},
    ]},
    {'label': _('Slideshows'), 'app_label': 'slideshow', 'items': [
        {'name': 'slideshow.SlideShow', 'label': _('Slideshow Management'),
         'url': {'type': 'model', 'app_label': 'slideshow', 'model': 'slideshow'}},
    ]},

]

#####################################################
#                 IMPORT_EXPORT                     #
#####################################################
IMPORT_EXPORT_USE_TRANSACTIONS = False

#####################################################
#                 BLOG CONFIG                       #
#####################################################
BLOG_FEED_LATEST_ITEMS = 5

BLOG_PLUGIN_TEMPLATE_FOLDERS = [('plugins', _('Default Template')), ('slider', _('Slider Template'))]
BLOG_MENU_TYPE = None

#####################################################
#             WYSIWIG EDITOR CONFIG                 #
#####################################################
TEXT_SAVE_IMAGE_FUNCTION = 'djangocms_text_ckeditor.picture_save.create_picture_plugin'
TEXT_ADDITIONAL_TAGS = ('iframe',)
TEXT_ADDITIONAL_ATTRIBUTES = ('scrolling', 'allowfullscreen', 'frameborder', 'src', 'height', 'width')
CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
    'toolbar_HTMLField': [
        ['Undo', 'Redo'],
        ['ShowBlocks'],
        ['Format', 'Styles'],
        ['Bold', 'Italic', 'Underline', '-', 'Subscript', 'Superscript', '-', 'RemoveFormat'],
    ],
    'skin': 'moono-lisa',
    'uiColor': '#ffffff'
}

#####################################################
#             COLLECTFAST CONFIG                    #
#####################################################
COLLECTFAST_ENABLED = True
AWS_PRELOAD_METADATA = True
COLLECTFAST_THREADS = 20
MAX_ENTRIES = 30000

if not DEBUG:
    THUMBNAIL_DEFAULT_STORAGE = os.environ['THUMBNAIL_DEFAULT_STORAGE']

#####################################################
#             DJANGO PODCAST CONFIG                 #
#####################################################
THUMBNAIL_ALIASES = {
    "podcasting.Show.original_image": {
        "sm": {"size": (120, 120)},
        "lg": {"size": (550, 550)},
        "itunes_sm": {"size": (144, 144)},
        "itunes_lg": {"size": (1400, 1400)},
    },
    "podcasting.Episode.original_image": {
        "sm": {"size": (120, 120)},
        "lg": {"size": (550, 550)},
        "itunes_sm": {"size": (144, 144)},
        "itunes_lg": {"size": (1400, 1400)},
    },
}

#####################################################
#             DJANGO CRON JOBS                      #
#####################################################
ALLOW_PARALLEL_RUNS = True
CRON_CLASSES = [
    'mailing.jobs.send_monthly_mails.SendStatistics',
]

FAILED_RUNS_CRONJOB_EMAIL_PREFIX = "[Django Cron Job Error]: "