# Generated by Django 2.0.13 on 2019-07-13 20:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelling', '0060_auto_20190708_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation', models.CharField(choices=[('SO', 'Self Organized'), ('CA', 'Camping'), ('CO', 'Simple Cottage'), ('HH', 'Holiday Home / Hunting Chalet'), ('LO', 'Lodge'), ('HC', 'Hunting Chalet'), ('HO', 'Hotel')], max_length=2, verbose_name='Accommodation type')),
                ('period', models.CharField(choices=[('D', 'Per day'), ('W', 'Per week'), ('M', 'Per month'), ('S', 'Per stay'), ('O', 'Other')], max_length=1, verbose_name='Billing period')),
                ('other_period', models.CharField(blank=True, max_length=150, null=True, verbose_name='Other billing period than selectable')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='GamePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('Y', 'Young'), ('X', 'No information')], max_length=1, null=True, verbose_name='Kind / Gender')),
                ('billing_range', models.CharField(choices=[('G', 'Per gram'), ('L', 'Per centimeter'), ('P', 'Per piece'), ('C', 'CIC points'), ('A', 'Age class'), ('O', 'Other range')], max_length=1, verbose_name='Billing range')),
                ('otherRange', models.CharField(blank=True, max_length=150, null=True, verbose_name='Other range')),
                ('minRange', models.IntegerField(default=1, help_text='Please only provide the numeric value here. E.g. 100 instead of 100cm', verbose_name='Start of range')),
                ('maxRange', models.IntegerField(help_text='Please only provide the numeric value here. E.g. 100 instead of 100cm', verbose_name='End of range')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_price', to='travelling.Game', verbose_name='Game')),
            ],
        ),
        migrations.CreateModel(
            name='OtherPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Should there be no choices available please select OTHER and provide your data in the appearing field.', max_length=150, null=True, verbose_name='Title')),
                ('billing_range', models.CharField(blank=True, max_length=150, null=True, verbose_name='Billing range')),
                ('minRange', models.IntegerField(blank=True, null=True, verbose_name='Start of range')),
                ('maxRange', models.IntegerField(blank=True, null=True, verbose_name='End of range')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='PackageTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Package name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('validityFrom', models.DateTimeField(verbose_name='Valid from')),
                ('validityTo', models.DateTimeField(verbose_name='Valid until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Package tour active')),
            ],
            options={
                'verbose_name': 'Package Tour',
                'verbose_name_plural': 'Package Tours',
                'ordering': ['-validityFrom', '-validityTo'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='XYZ', editable=False, max_length=3)),
                ('cost', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=8, verbose_name='Cost per period')),
                ('package_tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptour', to='pricing.PackageTour', verbose_name='Package tour')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Prices', max_length=150, verbose_name='Title')),
                ('validityFrom', models.DateField(verbose_name='Valid from')),
                ('validityTo', models.DateField(verbose_name='Valid until')),
                ('is_active', models.BooleanField(default=True, verbose_name='Price list active')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assoc_trip', to='travelling.Trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
                'ordering': ['-is_active', '-validityFrom', '-validityTo'],
            },
        ),
        migrations.AddField(
            model_name='price',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plist', to='pricing.PriceList', verbose_name='Price list'),
        ),
        migrations.AddField(
            model_name='packagetour',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='pricing.PriceList', verbose_name='Price list'),
        ),
        migrations.AddField(
            model_name='otherprice',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Price', verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='gameprice',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Price', verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='accommodationprice',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.Price', verbose_name='Price'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelist',
            unique_together={('trip', 'validityFrom', 'validityTo')},
        ),
    ]
