# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 14:53
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugin_directory_cardconfig', serialize=False, to='cms.CMSPlugin')),
                ('headline', models.CharField(max_length=50, null=True, verbose_name='Headline')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Card Body')),
                ('link', models.CharField(max_length=150, null=True, verbose_name='Forward URL')),
                ('btn_type', models.CharField(choices=[('success', 'Green Button'), ('danger', 'Red Button'), ('darkblue', 'Dark Blue Button'), ('light', 'Lightgray Button'), ('info', 'Lightblue Button')], default='success', max_length=25, verbose_name='Template')),
                ('btn_block', models.BooleanField(default=False, verbose_name='Display Button as Block')),
                ('link_text', models.CharField(max_length=35, null=True, verbose_name='Link Text')),
                ('template', models.CharField(choices=[('/Users/herbertwoisetschlager/coding/jagdreisencheck/cms_plugin_directory/templates/cms_plugin_templates/cards/blog-card.html', 'Blog-card.html'), ('/Users/herbertwoisetschlager/coding/jagdreisencheck/cms_plugin_directory/templates/cms_plugin_templates/cards/hover-card.html', 'Hover-card.html')], max_length=150, verbose_name='Template')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Top Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ColumnConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugin_directory_columnconfig', serialize=False, to='cms.CMSPlugin')),
                ('width', models.CharField(choices=[('1', '1/12'), ('2', '2/12'), ('3', '3/12'), ('4', '4/12'), ('5', '5/12'), ('6', '6/12'), ('7', '7/12'), ('8', '8/12'), ('9', '9/12'), ('10', '10/12'), ('11', '11/12'), ('12', '12/12')], max_length=7, null=True, verbose_name='Width')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ContainerConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugin_directory_containerconfig', serialize=False, to='cms.CMSPlugin')),
                ('container_type', models.CharField(choices=[('container', 'Regular Container'), ('container-fluid', 'Fluid Container')], max_length=35, null=True, verbose_name='Container Type')),
                ('margin_top', models.CharField(blank=True, max_length=7, null=True, verbose_name='Top Margin')),
                ('margin_bottom', models.CharField(blank=True, max_length=7, null=True, verbose_name='Bottom Margin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RowConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugin_directory_rowconfig', serialize=False, to='cms.CMSPlugin')),
                ('margin_top', models.CharField(blank=True, max_length=7, null=True, verbose_name='Top Margin')),
                ('margin_bottom', models.CharField(blank=True, max_length=7, null=True, verbose_name='Bottom Margin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
