# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugin_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardconfig',
            name='template',
            field=models.CharField(choices=[('/Users/herbertwoisetschlager/coding/jagdreisencheck-alpha/cms_plugin_directory/templates/cms_plugin_templates/cards/blog-card.html', 'Blog-card.html'), ('/Users/herbertwoisetschlager/coding/jagdreisencheck-alpha/cms_plugin_directory/templates/cms_plugin_templates/cards/hover-card.html', 'Hover-card.html')], max_length=150, verbose_name='Template'),
        ),
    ]
