# Generated by Django 2.1.7 on 2019-03-11 16:51

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugin_directory', '0002_auto_20181224_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardconfig',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_image', to=settings.FILER_IMAGE_MODEL, verbose_name='Top Image'),
        ),
    ]
