# Generated by Django 2.1.7 on 2019-03-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugin_directory', '0003_auto_20190311_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardconfig',
            name='template',
            field=models.CharField(choices=[('/Users/herbertwoisetschlager/coding/jagdreisencheck-webapplication/cms_plugin_directory/templates/cms_plugin_templates/cards/blog-card.html', 'Blog-card.html'), ('/Users/herbertwoisetschlager/coding/jagdreisencheck-webapplication/cms_plugin_directory/templates/cms_plugin_templates/cards/hover-card.html', 'Hover-card.html')], max_length=150, verbose_name='Template'),
        ),
    ]
