# Generated by Django 2.0.13 on 2019-06-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugin_directory', '0005_auto_20190530_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardconfig',
            name='template',
            field=models.CharField(choices=[('/Users/herbertwoisetschlager/coding/djangoweb/cms_plugin_directory/templates/cms_plugin_templates/cards/blog-card.html', 'Blog-card.html'), ('/Users/herbertwoisetschlager/coding/djangoweb/cms_plugin_directory/templates/cms_plugin_templates/cards/hover-card.html', 'Hover-card.html')], max_length=150, verbose_name='Template'),
        ),
    ]
