# Generated by Django 2.0.13 on 2019-09-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cms_plugin_directory', '0006_auto_20190604_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogThumbnailListConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugin_directory_blogthumbnaillistconfig', serialize=False, to='cms.CMSPlugin')),
                ('num_objects', models.IntegerField(default=3, max_length=1, verbose_name='Number of entries')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
