# Generated by Django 2.1.8 on 2019-05-03 11:05

import ckeditor.fields
from django.db import migrations, models
import django_countries.fields
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOCountryDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, unique=True, verbose_name='Country')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='Meta Description')),
                ('image1', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Image 1')),
                ('image2', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Image 2')),
                ('image3', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='Image 3')),
            ],
        ),
    ]
