# Generated by Django 2.0.13 on 2019-05-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seotools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seocountrydescriptor',
            options={'ordering': ['country']},
        ),
        migrations.AddField(
            model_name='seocountrydescriptor',
            name='keywords',
            field=models.TextField(help_text='Separate words by comma.', null=True, verbose_name='Keywords'),
        ),
    ]
