# Generated by Django 2.0.13 on 2019-05-03 18:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seotools', '0002_auto_20190503_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='seocountrydescriptor',
            name='meta_description',
            field=models.TextField(null=True, verbose_name='Meta-Description'),
        ),
        migrations.AlterField(
            model_name='seocountrydescriptor',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Description'),
        ),
    ]
