# Generated by Django 2.0.13 on 2019-05-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seotools', '0003_auto_20190503_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seocountrydescriptor',
            name='keywords',
            field=models.TextField(help_text='Separate words by comma. Generally the keywords jagdreisencheck, jagen, jagdreise, nachhaltige jagd, jagen weltweit, nachhaltigkeit are included!', null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='seocountrydescriptor',
            name='meta_description',
            field=models.TextField(help_text='Max. 140 characters.', max_length=140, null=True, verbose_name='Meta-Description'),
        ),
    ]
