# Generated by Django 2.0.13 on 2019-05-14 16:24

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seotools', '0004_auto_20190504_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInfoGraphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Headline')),
                ('body', models.TextField(blank=True, help_text='Text displayed below the slider graphic.', null=True, verbose_name='Body')),
                ('origin', models.CharField(choices=[('create_trip', 'Trip Creation'), ('rate_trip', 'Trip Rating'), ('trip_inquiry', 'Trip Inquiry')], max_length=15, null=True, verbose_name='User Origin')),
                ('order', models.PositiveIntegerField(null=True, verbose_name='Ordering')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to='', verbose_name='Slider Image')),
            ],
            options={
                'verbose_name': 'Registration Info Graphic',
                'verbose_name_plural': 'Registration Info Graphics',
                'ordering': ['order'],
            },
        ),
    ]
