# Generated by Django 2.0.13 on 2019-05-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seotools', '0005_registrationinfographic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinfographic',
            name='origin',
            field=models.CharField(choices=[('create_trip', 'Trip Creation'), ('rate_trip', 'Trip Rating'), ('trip_inquiry', 'Trip Inquiry'), ('default', 'Default (without a page reference)')], max_length=15, null=True, verbose_name='User Origin'),
        ),
    ]
