# Generated by Django 2.0.13 on 2019-05-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seotools', '0006_auto_20190514_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinfographic',
            name='date_created',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Date Created'),
        ),
    ]
