# Generated by Django 2.0.13 on 2019-05-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seotools', '0007_registrationinfographic_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinfographic',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Created'),
        ),
    ]
