# Generated by Django 2.1.7 on 2019-03-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jet', '0002_delete_userdashboardmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedapplication',
            name='user',
            field=models.CharField(max_length=255, verbose_name='user'),
        ),
    ]
