# Generated by Django 2.1.7 on 2019-03-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jet', '0003_auto_20190312_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.CharField(max_length=255, verbose_name='user'),
        ),
    ]
