# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 19:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181018_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CorporateProfile', verbose_name='Editor for a Company'),
        ),
    ]
