# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181025_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
    ]
