# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-04 22:36
from __future__ import unicode_literals

from django.db import migrations, models

import jagdreisencheck.global_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_companyname_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateprofile',
            name='logo',
        ),
        migrations.AddField(
            model_name='companyname',
            name='logo',
            field=models.ImageField(blank=True, height_field='profile_pic_height', null=True, upload_to='company_logos/', validators=[jagdreisencheck.global_helpers.validate_upload_size], verbose_name='Logo', width_field='profile_pic_width'),
        ),
    ]
