# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181104_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='profile_pic_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='companyname',
            name='profile_pic_width',
            field=models.IntegerField(null=True),
        ),
    ]
