# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import image_optimizer.fields
import jagdreisencheck.global_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20181121_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='logo',
            field=image_optimizer.fields.OptimizedImageField(blank=True, height_field='profile_pic_height', null=True, upload_to='company_logos/', validators=[jagdreisencheck.global_helpers.validate_upload_size], verbose_name='Title Image', width_field='profile_pic_width'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='preferred_hunting_type',
            field=models.CharField(blank=True, choices=[('P', 'Stalking'), ('A', 'Stand Hunting'), ('G', 'Joint Hunting')], max_length=2, null=True, verbose_name='Preferred Hunting Type'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='profile_pic',
            field=image_optimizer.fields.OptimizedImageField(blank=True, height_field='profile_pic_height', null=True, upload_to='profile_pictures/', validators=[jagdreisencheck.global_helpers.validate_upload_size], verbose_name='Profile Picture', width_field='profile_pic_width'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='title_pic',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='title_images/', verbose_name='Title Image'),
        ),
    ]
