# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 14:31
from __future__ import unicode_literals

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181128_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateprofile',
            name='title_pic',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='title_images/', verbose_name='Title Image'),
        ),
    ]
