# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 14:34
from __future__ import unicode_literals

from django.db import migrations
import image_optimizer.fields
import jagdreisencheck.global_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_corporateprofile_title_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyname',
            old_name='profile_pic_height',
            new_name='logo_height',
        ),
        migrations.RenameField(
            model_name='companyname',
            old_name='profile_pic_width',
            new_name='logo_width',
        ),
        migrations.AlterField(
            model_name='companyname',
            name='logo',
            field=image_optimizer.fields.OptimizedImageField(blank=True, height_field='logo_height', null=True, upload_to='company_logos/', validators=[jagdreisencheck.global_helpers.validate_upload_size], verbose_name='Logo', width_field='logo_width'),
        ),
    ]
