# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181128_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofile',
            name='email_visibility',
            field=models.CharField(choices=[('E', 'Everyone'), ('M', 'Logged-in Users Only'), ('N', 'Nobody')], default='N', max_length=1, verbose_name='E-Mail Visibility'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='profile_pic_visibility',
            field=models.CharField(choices=[('E', 'Everyone'), ('M', 'Logged-in Users Only'), ('N', 'Nobody')], default='M', max_length=2, verbose_name='Profile Picture Visibility'),
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='title_pic_visibility',
            field=models.CharField(choices=[('E', 'Everyone'), ('M', 'Logged-in Users Only'), ('N', 'Nobody')], default='M', max_length=2, verbose_name='Title Image Visibility'),
        ),
    ]
