# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181211_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='individualprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'No information')], max_length=2, null=True, verbose_name='Gender'),
        ),
    ]
