# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-05 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190104_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='First Name'),
            preserve_default=False,
        ),
    ]
