# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20190105_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Please provide your e-mail address that you will use to log in.', max_length=70, unique=True, verbose_name='E-Mail'),
        ),
    ]
