# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 14:02
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190108_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_of_residence',
            field=django_countries.fields.CountryField(help_text="Please provide the country you're living in here.", max_length=2, verbose_name='Country'),
        ),
    ]
