# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190108_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="Please provide the company's public email address where potential customers can contact you.", max_length=254, null=True, unique=True, verbose_name='Contact E-Mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Please provide your password here. It must contain at least 1 lower case letter, 1 upper case letter and 1 numeric character. The minimum length is 8 characters.', max_length=128, verbose_name='password'),
        ),
    ]
