# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190108_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofile',
            name='email_newsletter',
            field=models.CharField(choices=[('M', 'Important E-Mails + Newsletter'), ('I', 'Important E-Mails only')], default='M', max_length=1, verbose_name='News on Jagdreisencheck'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Please provide your password here. It must contain at least 1 letter, 1 numeric character and one special character (e.g. ?). The minimum length is 8 characters.', max_length=128, verbose_name='password'),
        ),
    ]
