# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 15:29
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20190108_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateprofile',
            name='country',
            field=django_countries.fields.CountryField(help_text="This is the country where your firm's headquarter is in.", max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_of_residence',
            field=django_countries.fields.CountryField(help_text="Please provide the country you're living in here.", max_length=2, verbose_name='Home Country'),
        ),
    ]
