# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20190115_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateprofile',
            name='homepage',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Homepage'),
        ),
    ]
