# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-18 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20190116_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyname',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="Please provide the company's public email address where potential customers can contact you.", max_length=254, null=True, verbose_name='Contact E-Mail'),
        ),
    ]
