# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-11 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190211_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofile',
            name='hunting_license',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], help_text='Please indicated if you own a hunting license. This is required as we focus on sustainable hunting and that includes that hunters that use our platform must have a formal qualification for hunting.', verbose_name='Hunting Licence'),
        ),
    ]
