# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-17 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190211_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofile',
            name='birth_date',
            field=models.DateField(error_messages={'invalid': 'Please provide a valid date. Format: dd.mm.yyyy'}, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'User with this e-mail already exists.'}, help_text='Please provide your e-mail address that you will use to log in.', max_length=70, unique=True, verbose_name='E-Mail'),
        ),
    ]
