# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-18 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20190217_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_inquiries',
            field=models.IntegerField(default=5, verbose_name='Remaining Inquiries'),
        ),
    ]
