# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-18 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20190218_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='next_inquiries_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 2, 18, 21, 0, 43, 239839, tzinfo=utc), null=True, verbose_name='Next Inquiries'),
        ),
    ]
