# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20190218_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='next_inquiries_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Inquiries'),
        ),
    ]
