# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20190218_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateprofile',
            name='has_lead_contract',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Contracted for leads'),
        ),
    ]
