# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_corporateprofile_has_lead_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateprofile',
            name='headline_image_position',
            field=models.IntegerField(default=0, null=True, verbose_name='Title Picture Position'),
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='headline_image_position',
            field=models.IntegerField(default=0, null=True, verbose_name='Title Picture Position'),
        ),
    ]
