# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20190222_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateprofile',
            name='phone',
            field=models.CharField(help_text='Please provide your public phone number. Please DO NOT use country codes, instead provide the local format: 01234 000000000', max_length=50, verbose_name='Phone'),
        ),
    ]
