# Generated by Django 2.1.7 on 2019-03-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_group_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateprofile',
            name='phone',
            field=models.CharField(help_text='Please provide your public phone number. Please DO NOT use country codes, instead provide the local format: 01234 000000000. Characters "+" and "/" are NOT allowed.', max_length=50, verbose_name='Phone'),
        ),
    ]
