# Generated by Django 2.1.7 on 2019-03-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20190321_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateprofile',
            name='operator_type',
            field=models.CharField(choices=[('AGENT', 'Travel Agent'), ('PROVIDER', 'Travel Provider')], default='AGENT', max_length=8, null=True, verbose_name='Are you a travel agent or direct provider?'),
        ),
    ]
