# Generated by Django 2.1.7 on 2019-03-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_corporateprofile_operator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referral Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referred By - Code'),
        ),
    ]
