# Generated by Django 2.1.8 on 2019-04-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20190402_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyname',
            options={'ordering': ['name'], 'verbose_name': 'Company Name', 'verbose_name_plural': 'Company Names'},
        ),
        migrations.AddField(
            model_name='corporateprofile',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Last modified'),
        ),
    ]
