# Generated by Django 2.0.13 on 2019-05-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20190416_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('Y', 'Young'), ('X', 'No information')], max_length=2, null=True, verbose_name='Gender'),
        ),
    ]
