# Generated by Django 2.1.9 on 2019-06-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20190531_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('X', 'No information')], max_length=2, null=True, verbose_name='Gender'),
        ),
    ]
