# Generated by Django 2.1.9 on 2019-07-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20190617_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('X', 'No information')], max_length=2, null=True, verbose_name='Gender'),
        ),
    ]
