# Generated by Django 2.0.13 on 2019-05-05 12:31

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import filer.fields.file
import podcasting.models
import podcasting.utils.fields
import sorl.thumbnail.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('filer', '0010_auto_20180414_2058'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', embed_video.fields.EmbedVideoField(help_text='URL of the media file', verbose_name='url')),
            ],
            options={
                'verbose_name': 'Embed Media URL',
                'verbose_name_plural': 'Embed Media URLs',
                'ordering': ('episode', 'url'),
            },
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='URL of the media file. <br /> It is <strong>very</strong>\n            important to remember that for episode artwork to display in iTunes, image must be\n            <a href="http://answers.yahoo.com/question/index?qid=20080501164348AAjvBvQ">\n            saved to file\'s <strong>metadata</strong></a> before enclosure uploading!<br /><br />\n            For best results, choose an attractive, original, and square JPEG (.jpg) or PNG (.png)\n            image at a size of 1400x1400 pixels. The image will be\n            scaled down to 50x50 pixels at smallest in iTunes.', null=True, verbose_name='url')),
                ('size', models.PositiveIntegerField(help_text='The length attribute is the file size in bytes. Find this information in the files properties (on a Mac, ``Get Info`` and refer to the size row)', verbose_name='size')),
                ('mime', models.CharField(choices=[('aiff', 'audio/aiff'), ('flac', 'audio/flac'), ('mp3', 'audio/mpeg'), ('mp4', 'audio/mp4'), ('ogg', 'audio/ogg'), ('flac', 'audio/flac'), ('wav', 'audio/wav')], help_text='Supports mime types of: aiff, flac, mp3, mp4, ogg, flac, wav', max_length=4, verbose_name='mime format')),
                ('bitrate', models.CharField(default='192', help_text='Measured in kilobits per second (kbps), often 128 or 192.', max_length=5, verbose_name='bit rate')),
                ('sample', models.CharField(default='44.1', help_text='Measured in kilohertz (kHz), often 44.1.', max_length=5, verbose_name='sample rate')),
                ('channel', models.CharField(default=2, help_text='Number of channels; 2 for stereo, 1 for mono.', max_length=1, verbose_name='channel')),
                ('duration', models.IntegerField(help_text='Duration of the audio file, in seconds (always as integer).', verbose_name='duration')),
            ],
            options={
                'verbose_name': 'Enclosure',
                'verbose_name_plural': 'Enclosures',
                'ordering': ('url', 'mime'),
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', podcasting.utils.fields.UUIDField(blank=True, editable=False, max_length=36, unique=True, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('published', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='published')),
                ('enable_comments', models.BooleanField(default=True)),
                ('author_text', models.CharField(blank=True, help_text="\n        The person or musician name(s) featured on this specific episode.\n        The suggested format is: 'email@example.com (Full Name)' but 'Full Name' only,\n        is acceptable. Multiple authors should be comma separated.", max_length=255, verbose_name='author text')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique='True', verbose_name='slug')),
                ('subtitle', models.CharField(blank=True, help_text='Looks best if only a few words like a tagline.', max_length=255, verbose_name='subtitle')),
                ('description_pretty', models.TextField(blank=True, help_text='May be longer than 4000 characters and contain HTML tags and styling.', verbose_name='pretty description')),
                ('description', models.TextField(blank=True, help_text="\n            This is your chance to tell potential subscribers all about your podcast.\n            Describe your subject matter, media format, episode schedule, and other\n            relevant info so that they know what they'll be getting when they\n            subscribe. In addition, make a list of the most relevant search terms\n            that you want your podcast to match, then build them into your\n            description. Note that iTunes removes podcasts that include lists of\n            irrelevant words in the itunes:summary, description, or\n            itunes:keywords tags. This field can be up to 4000 plain text characters.\n            No HTML tags or styling allowed.", max_length=4000, verbose_name='description')),
                ('tracklist', models.TextField(blank=True, help_text='One track per line, machine will automatically add the numbers.', verbose_name='tracklist')),
                ('tweet_text', models.CharField(editable=False, max_length=140, verbose_name='tweet text')),
                ('original_image', sorl.thumbnail.fields.ImageField(blank=True, help_text='\n                A podcast must have 1400 x 1400 pixel cover art in JPG or PNG\n                format using RGB color space. See our technical spec for\n                details. To be eligible for featuring on iTunes Stores,\n                choose an attractive, original, and square JPEG (.jpg) or\n                PNG (.png) image at a size of 1400x1400 pixels. The image\n                will be scaled down to 50x50 pixels at smallest in iTunes.\n                For reference see the <a\n                href="http://www.apple.com/itunes/podcasts/specs.html#metadata">iTunes\n                Podcast specs</a>.<br /><br /> For episode artwork to\n                display in iTunes, image must be <a\n                href="http://answers.yahoo.com/question/index?qid=20080501164348AAjvBvQ">\n                saved to file\'s <strong>metadata</strong></a> before\n                enclosure uploading!', upload_to=podcasting.models.get_episode_upload_folder, verbose_name='image')),
                ('hours', models.SmallIntegerField(default=0, verbose_name='hours')),
                ('minutes', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59)], default=0, verbose_name='minutes')),
                ('seconds', models.SmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59)], default=0, verbose_name='seconds')),
                ('keywords', models.CharField(blank=True, help_text='A comma-delimited list of words for searches, up to 12; perhaps include misspellings.', max_length=255, verbose_name='keywords')),
                ('explicit', models.PositiveSmallIntegerField(choices=[(1, 'yes'), (2, 'no'), (3, 'clean')], default=1, help_text='``Clean`` will put the clean iTunes graphic by it.', verbose_name='explicit')),
                ('block', models.BooleanField(default=False, help_text='Check to block this episode from iTunes because <br />its content might cause the entire show to be <br />removed from iTunes.', verbose_name='block')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ('-published', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', podcasting.utils.fields.UUIDField(blank=True, editable=False, max_length=36, unique=True, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('published', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='published')),
                ('ttl', models.PositiveIntegerField(default=1440, help_text='``Time to Live,`` the number of minutes a channel can be\n        cached before refreshing.', verbose_name='ttl')),
                ('editor_email', models.EmailField(blank=True, help_text="Email address of the person responsible for the feed's content.", max_length=254, verbose_name='editor email')),
                ('webmaster_email', models.EmailField(blank=True, help_text='Email address of the person responsible for channel publishing.', max_length=254, verbose_name='webmaster email')),
                ('license', models.CharField(blank=True, help_text='To publish a podcast to iTunes it is required to set a license type.', max_length=255, null=True, verbose_name='license')),
                ('organization', models.CharField(help_text='Name of the organization, company or Web site producing the podcast.', max_length=255, verbose_name='organization')),
                ('link', models.URLField(help_text='URL of either the main website or the\n        podcast section of the main website.', verbose_name='link')),
                ('enable_comments', models.BooleanField(default=True)),
                ('author_text', models.CharField(help_text="\n            This tag contains the name of the person or company that is most\n            widely attributed to publishing the Podcast and will be\n            displayed immediately underneath the title of the Podcast.\n            The suggested format is: 'email@example.com (Full Name)'\n            but 'Full Name' only, is acceptable. Multiple authors\n            should be comma separated.", max_length=255, verbose_name='author text')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique='True', verbose_name='slug')),
                ('subtitle', models.CharField(help_text='Looks best if only a few words, like a tagline.', max_length=255, verbose_name='subtitle')),
                ('on_itunes', models.BooleanField(default=True, help_text='Checked if the podcast is submitted to iTunes', verbose_name='iTunes')),
                ('description_pretty', models.TextField(blank=True, help_text='May be longer than 4000 characters and contain HTML tags and styling.', verbose_name='pretty description')),
                ('description', models.TextField(help_text="\n            This is your chance to tell potential subscribers all about your\n            podcast. Describe your subject matter, media format,\n            episode schedule, and other relevant info so that they\n            know what they'll be getting when they subscribe. In\n            addition, make a list of the most relevant search terms\n            that you want yourp podcast to match, then build them into\n            your description. Note that iTunes removes podcasts that\n            include lists of irrelevant words in the itunes:summary,\n            description, or itunes:keywords tags. This field can be up\n            to 4000 characters.", max_length=4000, verbose_name='description')),
                ('original_image', sorl.thumbnail.fields.ImageField(blank=True, help_text='\n                A podcast must have 1400 x 1400 pixel cover art in JPG or PNG\n                format using RGB color space. See our technical spec for\n                details. To be eligible for featuring on iTunes Stores,\n                choose an attractive, original, and square JPEG (.jpg) or\n                PNG (.png) image at a size of 1400x1400 pixels. The image\n                will be scaled down to 50x50 pixels at smallest in iTunes.\n                For reference see the <a\n                href="http://www.apple.com/itunes/podcasts/specs.html#metadata">iTunes\n                Podcast specs</a>.<br /><br /> For episode artwork to\n                display in iTunes, image must be <a\n                href="http://answers.yahoo.com/question/index?qid=20080501164348AAjvBvQ">\n                saved to file\'s <strong>metadata</strong></a> before\n                enclosure uploading!', upload_to=podcasting.models.get_show_upload_folder, verbose_name='image')),
                ('feedburner', models.URLField(blank=True, help_text='Fill this out after saving this show and at least one\n            episode. URL should look like "http://feeds.feedburner.com/TitleOfShow".\n            See <a href="http://code.google.com/p/django-podcast/">documentation</a>\n            for more. <a href="http://www.feedburner.com/fb/a/ping">Manually ping</a>', verbose_name='feedburner url')),
                ('explicit', models.PositiveSmallIntegerField(choices=[(1, 'yes'), (2, 'no'), (3, 'clean')], default=1, help_text='``Clean`` will put the clean iTunes graphic by it.', verbose_name='explicit')),
                ('redirect', models.URLField(blank=True, help_text="The show's new URL feed if changing\n            the URL of the current show feed. Must continue old feed for at least\n            two weeks and write a 301 redirect for old feed.", verbose_name='redirect')),
                ('keywords', models.CharField(blank=True, help_text='A comma-demlimitedlist of up to 12 words for iTunes\n            searches. Perhaps include misspellings of the title.', max_length=255, verbose_name='keywords')),
                ('itunes', models.URLField(blank=True, help_text='Fill this out after saving this show and at least one\n            episode. URL should look like:\n            "http://phobos.apple.com/WebObjects/MZStore.woa/wa/viewPodcast?id=000000000".\n            See <a href="http://code.google.com/p/django-podcast/">documentation</a> for more.', verbose_name='itunes store url')),
                ('twitter_tweet_prefix', models.CharField(blank=True, help_text='Enter a short ``tweet_text`` prefix for new episodes on this show.', max_length=80, verbose_name='Twitter tweet prefix')),
                ('owner', models.ForeignKey(help_text='Make certain the user account has a name and e-mail address.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcast_shows', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('sites', models.ManyToManyField(to='sites.Site', verbose_name='Sites')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
                'ordering': ('organization', 'slug'),
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='shows',
            field=models.ManyToManyField(to='podcasting.Show', verbose_name='Podcasts'),
        ),
        migrations.AddField(
            model_name='episode',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='enclosure',
            name='episodes',
            field=models.ManyToManyField(to='podcasting.Episode', verbose_name='Episodes'),
        ),
        migrations.AddField(
            model_name='enclosure',
            name='file',
            field=filer.fields.file.FilerFileField(help_text='Please upload the audio track here. Duration and size are unlimited.', on_delete=django.db.models.deletion.CASCADE, to='filer.File', verbose_name='Audio Track'),
        ),
        migrations.AddField(
            model_name='embedmedia',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasting.Episode', verbose_name='episode'),
        ),
        migrations.AlterUniqueTogether(
            name='embedmedia',
            unique_together={('episode', 'url')},
        ),
    ]
