# Generated by Django 2.0.13 on 2019-05-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('published', 'slug'), 'verbose_name': 'Episode', 'verbose_name_plural': 'Episodes'},
        ),
        migrations.AlterField(
            model_name='enclosure',
            name='mime',
            field=models.CharField(choices=[('aiff', 'audio/aiff'), ('flac', 'audio/flac'), ('mp3', 'audio/mp3 (mpeg)'), ('mp4', 'audio/mp4'), ('ogg', 'audio/ogg'), ('flac', 'audio/flac'), ('wav', 'audio/wav')], help_text='Supports mime types of: aiff, flac, mp3, mp4, ogg, flac, wav', max_length=4, verbose_name='mime format'),
        ),
    ]
