# Generated by Django 2.1.7 on 2019-03-12 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slideshow/%Y/%m/%d/', verbose_name='Image File')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Image caption')),
            ],
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, null=True, verbose_name='Slideshow Title')),
                ('target_model', models.CharField(max_length=150, null=True, verbose_name='Associated Model')),
                ('identifier', models.CharField(max_length=30, null=True, verbose_name='Model Identifier')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Date Modified')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owning User')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='slideshow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='slideshow.SlideShow', verbose_name='Slideshow'),
        ),
        migrations.AlterUniqueTogether(
            name='slideshow',
            unique_together={('target_model', 'identifier')},
        ),
    ]
