# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConfig',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='search_searchconfig', serialize=False, to='cms.CMSPlugin')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('fields', models.CharField(max_length=400, null=True, verbose_name='Model Fields')),
                ('template', models.CharField(choices=[('/Users/herbertwoisetschlager/coding/jagdreisencheck/search/templates/search/results', 'Results'), ('/Users/herbertwoisetschlager/coding/jagdreisencheck/search/templates/search/large_search_bar.html', 'Large Search Bar.html')], max_length=300, verbose_name='Template')),
                ('available_to_anonymous', models.BooleanField(default=True, verbose_name='May unauthenticated users use this search instance?')),
                ('collect_metrics', models.BooleanField(default=False, verbose_name='Collect Metrics')),
                ('show_help', models.BooleanField(default=False, verbose_name='Show Help Texts')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='DB Model')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
