# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchconfig',
            name='template',
            field=models.CharField(choices=[('/Users/herbertwoisetschlager/coding/jagdreisencheck-alpha/search/templates/search/results', 'Results'), ('/Users/herbertwoisetschlager/coding/jagdreisencheck-alpha/search/templates/search/large_search_bar.html', 'Large Search Bar.html')], max_length=300, verbose_name='Template'),
        ),
    ]
