# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20181224_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchconfig',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='searchconfig',
            name='model',
        ),
        migrations.RemoveField(
            model_name='searchconfig',
            name='template',
        ),
    ]
