# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 09:24
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0002_auto_20181127_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprice',
            name='trophy_costs',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=8, null=True, verbose_name='Trophy Costs'),
        ),
        migrations.AlterField(
            model_name='gameprice',
            name='wounded_costs',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=8, null=True, verbose_name='Wounded costs'),
        ),
    ]
