# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0004_auto_20181128_1127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accommodationprice',
            unique_together=set([('acc_type', 'price_list')]),
        ),
    ]
