# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 14:24
from __future__ import unicode_literals

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0005_auto_20181128_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='headline_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='trips/headline_images/', verbose_name='Title Image'),
        ),
    ]
