# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0006_auto_20181128_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationprice',
            name='acc_type',
            field=models.CharField(choices=[('SO', 'Self Organized'), ('CA', 'Camping'), ('CO', 'Simple Cottage'), ('HH', 'Holiday Home'), ('LO', 'Lodge'), ('HC', 'Hunting Chalet'), ('HO', 'Hotel')], max_length=2, null=True, verbose_name='Accommodation'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='accommodation_type',
            field=models.CharField(choices=[('SO', 'Self Organized'), ('CA', 'Camping'), ('CO', 'Simple Cottage'), ('HH', 'Holiday Home'), ('LO', 'Lodge'), ('HC', 'Hunting Chalet'), ('HO', 'Hotel')], default='S', max_length=2, null=True, verbose_name='Accommodation Type'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.CharField(max_length=75, null=True, verbose_name='Absolute URL'),
        ),
    ]
