# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0007_auto_20181211_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Absolute URL'),
        ),
    ]
