# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0008_auto_20181213_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rating Count'),
        ),
    ]
