# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0009_trip_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='hunting_end_time',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=10, null=True, verbose_name='End of Season'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hunting_start_time',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=5, null=True, verbose_name='Start of Season'),
        ),
    ]
