# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0010_auto_20181221_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.CharField(max_length=90, null=True, verbose_name='Title of your review'),
        ),
    ]
