# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0011_auto_20181221_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelinquiry',
            name='status',
        ),
        migrations.AddField(
            model_name='travelinquiry',
            name='traveller_status',
            field=models.CharField(choices=[('OP', 'Open'), ('OS', 'Offer sent'), ('FU', 'Follow up required'), ('OA', 'Offer accepted'), ('PR', 'Payment received'), ('CT', 'Customer on trip'), ('CT', 'Customer returned'), ('IR', 'Customer invited for review'), ('RR', 'Review received'), ('CL', 'Closed')], default='OP', max_length=2, verbose_name='Travel Status'),
        ),
    ]
