# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0012_auto_20181227_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameprice',
            old_name='calc_base',
            new_name='calculation',
        ),
        migrations.RenameField(
            model_name='gameprice',
            old_name='base_range',
            new_name='range',
        ),
        migrations.AlterUniqueTogether(
            name='gameprice',
            unique_together=set([('game', 'type', 'range')]),
        ),
    ]
