# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0013_auto_20190104_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='more_details_pdf',
            field=models.FileField(blank=True, null=True, upload_to='files/trip_descriptions/', verbose_name='PDF with detailed information'),
        ),
    ]
