# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-05 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0014_trip_more_details_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='check_strike_pos',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Have you had the opportunity to check your strike position?'),
        ),
    ]
