# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0016_auto_20190108_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='dog_purpose',
            field=models.CharField(blank=True, choices=[('NH', 'Chasing Dogs'), ('DR', 'Joint Hunt'), ('PI', 'Stalking Support')], max_length=3, null=True, verbose_name='What did you use the dogs for?'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='game_age_dist',
            field=models.IntegerField(choices=[(1, 'Too young'), (3.0000000000001, 'Rather too young'), (5, 'Optimal'), (3, 'Rather too old'), (1, 'Too old'), (0, 'Unknown')], null=True, verbose_name="How was the wildlife's age distributed?"),
        ),
        migrations.AlterField(
            model_name='rating',
            name='game_density',
            field=models.IntegerField(choices=[(1, 'Too sparse'), (3.0000000000001, 'Rather too sparse'), (5, 'Optimal density'), (3, 'Rather too dense'), (1, 'Too dense'), (0, 'Unknown')], null=True, verbose_name='How dense was the wildlife?'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='game_gender_dist',
            field=models.IntegerField(choices=[(1, 'Predominantly female game'), (3.0000000000001, 'Slight overweight of female game'), (5, 'Good gender distribution'), (3, 'Slight overweight of male game'), (1, 'Predominantly male game'), (0, 'Unknown')], null=True, verbose_name="How did you experience the wildlife's gender distribution?"),
        ),
    ]
