# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-09 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0018_auto_20190109_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinquiry',
            name='num_of_hunters',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Hunters'),
        ),
        migrations.AlterField(
            model_name='travelinquiry',
            name='num_of_non_hunters',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of accompanying Persons'),
        ),
    ]
