# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0019_auto_20190109_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationprice',
            name='acc_type',
            field=models.CharField(choices=[('SO', 'Self Organized'), ('CA', 'Camping'), ('CO', 'Simple Cottage'), ('HH', 'Holiday Home / Hunting Chalet'), ('LO', 'Lodge'), ('HC', 'Hunting Chalet'), ('HO', 'Hotel')], max_length=2, null=True, verbose_name='Accommodation'),
        ),
        migrations.AlterField(
            model_name='gameprice',
            name='type',
            field=models.CharField(max_length=75, null=True, verbose_name='Gender/Type'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='accommodation_type',
            field=models.CharField(choices=[('SO', 'Self Organized'), ('CA', 'Camping'), ('CO', 'Simple Cottage'), ('HH', 'Holiday Home / Hunting Chalet'), ('LO', 'Lodge'), ('HC', 'Hunting Chalet'), ('HO', 'Hotel')], default='S', max_length=2, null=True, verbose_name='Accommodation Type'),
        ),
        migrations.AlterField(
            model_name='travelinquiry',
            name='traveller_status',
            field=models.CharField(choices=[('OP', 'Open'), ('FC', 'First contact'), ('OS', 'Offer sent'), ('FU', 'Follow up required'), ('OA', 'Offer accepted'), ('PR', 'Payment received'), ('CT', 'Customer on trip'), ('CT', 'Customer returned'), ('IR', 'Customer invited for review'), ('RR', 'Review received'), ('CL', 'Closed')], default='OP', max_length=2, verbose_name='Travel Status'),
        ),
    ]
