# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0020_auto_20190115_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinquiry',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Inquiry has been opened'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='alternative_activities',
            field=models.NullBooleanField(choices=[(False, 'No'), (True, 'Yes'), (None, 'Unknown')], default=None, help_text='Is there an oportunity to spend time besides hunting activities?', verbose_name='Alternative Offers'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='broadband_internet',
            field=models.NullBooleanField(choices=[(False, 'No'), (True, 'Yes'), (None, 'Unknown')], default=None, help_text='Please indicate if hunters can access the internet via WiFi.', verbose_name='Broadband Internet'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hunting_end_time',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=10, help_text='Please provide the end of the hunting season.', null=True, verbose_name='End of Season'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hunting_start_time',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=5, help_text='Please provide the start of the hunting season.', null=True, verbose_name='Start of Season'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='interpreter_at_site',
            field=models.NullBooleanField(choices=[(False, 'No'), (True, 'Yes'), (None, 'Unknown')], default=None, help_text='Please indicate if there is an interpreting service at the hunting sight.', verbose_name='Interpreting Service'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='private_parking',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, help_text='Please indicate if hunters who arrive by car can park their car on property.', verbose_name='Private Parking'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='wireless_coverage',
            field=models.NullBooleanField(choices=[(False, 'No'), (True, 'Yes'), (None, 'Unknown')], default=None, help_text='Please indicate if hunters have mobile network access at your property.', verbose_name='Wireless Coverage'),
        ),
    ]
