# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-11 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0024_auto_20190123_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='economic_rating',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='rating_economic',
        ),
        migrations.AlterField(
            model_name='rating',
            name='alternative_program',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, help_text='Please indicate if you did activities besides hunting such as hiking, sightseeing.', verbose_name='Did you make use of alternative program'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='headline_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, help_text='Please do NOT upload images that show a lot of blood, posing or other situations that may be offensive to people that are not familiar with hunting!', null=True, upload_to='trips/headline_images/', verbose_name='Title Image'),
        ),
    ]
