# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-11 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0025_auto_20190211_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='organization_of_hunt',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Rather Bad'), (3, 'Neutral'), (4, 'Rather Good'), (5, 'Good')], null=True, verbose_name='Quality of the hunting organization'),
        ),
    ]
