# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-15 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0026_rating_organization_of_hunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='accommodation_rating',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Rather Bad'), (3, 'Neutral'), (4, 'Rather Good'), (5, 'Good')], help_text='Please rate the accommodation you had during your stay. Even a camping sight may get 5 stars if everything was fine.', null=True, verbose_name='Accommodation Rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='alternative_program',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, help_text='Please indicate if you did activities besides hunting such as hiking or sightseeing.', verbose_name='Did you make use of alternative program'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='check_strike_pos',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, help_text='Did you have the opportunity to check your rifle and take some validation shots?', verbose_name='Have you had the opportunity to check your strike position?'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='communication_quality',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Rather Bad'), (3, 'Neutral'), (4, 'Rather Good'), (5, 'Good')], help_text='How was the communication with the local employees? Did you experience any inconveniences?', null=True, verbose_name='Communication between staff and yourself'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='customer_support',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Rather Bad'), (3, 'Neutral'), (4, 'Rather Good'), (5, 'Good')], help_text='How was the communication with the operator? Did you get assistance with registering your rifle and with bureaucratic processes? Were you told what vaccinations you need?', null=True, verbose_name='Customer Support'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='game_age_dist',
            field=models.IntegerField(choices=[(1, 'Too young'), (3, 'Rather too young'), (5, 'Optimal'), (3, 'Rather too old'), (1, 'Too old'), (0, 'Unknown')], help_text='Were there more older or younger pieces? Did you experience a pyramidal structure?', null=True, verbose_name="How was the wildlife's age distributed?"),
        ),
        migrations.AlterField(
            model_name='rating',
            name='game_density',
            field=models.IntegerField(choices=[(1, 'Too sparse'), (3, 'Rather too sparse'), (5, 'Optimal density'), (3, 'Rather too dense'), (1, 'Too dense'), (0, 'Unknown')], help_text='Did you experience a good game density or was there too much/few game?', null=True, verbose_name='How dense was the wildlife?'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='game_gender_dist',
            field=models.IntegerField(choices=[(1, 'Predominantly female game'), (3, 'Slight overweight of female game'), (5, 'Good gender distribution'), (3, 'Slight overweight of male game'), (1, 'Predominantly male game'), (0, 'Unknown')], help_text='Did you experience a well distributed structure (50/50 female/male)?', null=True, verbose_name="How did you experience the wildlife's gender distribution?"),
        ),
        migrations.AlterField(
            model_name='rating',
            name='hunt_in_wilderness',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, help_text='If you have pursued a gate hunt then the game was not living in the wild.', verbose_name='Did you hunt in the wilderness?'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='hunting_introduction',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Rather Bad'), (3, 'Neutral'), (4, 'Rather Good'), (5, 'Good')], help_text='How well did the operator prepare you for your hunt? Did they tell you about laws and good practices?', null=True, verbose_name='Introduction to local hunting conditions'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='professional_hunter_quality',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Rather Bad'), (3, 'Neutral'), (4, 'Rather Good'), (5, 'Good')], help_text="Please objectively rate the professional hunter's abilities and leave out personal impressions. This question is purely about his abilities.", null=True, verbose_name='Quality of the professional hunter'),
        ),
    ]
