# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-17 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0027_auto_20190215_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinquiry',
            name='time_end',
            field=models.DateField(error_messages={'invalid': 'Please provide a valid date. Format: dd.mm.yyyy'}, null=True, verbose_name='When would you like to end the trip?'),
        ),
        migrations.AlterField(
            model_name='travelinquiry',
            name='time_start',
            field=models.DateField(error_messages={'invalid': 'Please provide a valid date. Format: dd.mm.yyyy'}, null=True, verbose_name='When would you like to start the trip?'),
        ),
    ]
