# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-18 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0028_auto_20190217_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinquiry',
            name='kind_of_inquiry',
            field=models.CharField(choices=[('ST', 'Solo Travel'), ('GT', 'Group Travel'), ('OT', 'Other')], max_length=2, null=True, verbose_name='Kind of Inquiry'),
        ),
    ]
