# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0029_auto_20190218_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='customer_support',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Rather Bad'), (3, 'Neutral'), (4, 'Rather Good'), (5, 'Good')], help_text='How convenient was the communication with the operator? Did the operator assist you with bureaucratic processes?', null=True, verbose_name='Customer Support'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='organization_of_hunt',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Rather Bad'), (3, 'Neutral'), (4, 'Rather Good'), (5, 'Good')], help_text='Please rate the hunt-related admin quality. Did your hunts start on time? Were there enough vehicles? How was the condition of hunting facilities?', null=True, verbose_name='Quality of the hunting organization'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='support_with_issues',
            field=models.IntegerField(choices=[(1, 'Bad'), (2, 'Rather Bad'), (3, 'Neutral'), (4, 'Rather Good'), (5, 'Good')], help_text='How was the communication with the operator? Did you get assistance with registering your rifle and with bureaucratic processes? Were you told what vaccinations you need?', null=True, verbose_name='Operator Support with Issues'),
        ),
    ]
