# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0030_auto_20190219_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='region',
            field=models.CharField(help_text='Please provide the territory or region name here. Please note that you may only offer one trip per territory or region.', max_length=300, verbose_name='Region / Territory'),
        ),
    ]
