# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-19 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0031_auto_20190219_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinquiry',
            name='read',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Inquiry has been opened'),
        ),
    ]
