# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-20 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0032_auto_20190219_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='Trip Description'),
        ),
    ]
