# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-21 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import image_optimizer.fields
import jagdreisencheck.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0033_auto_20190220_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='headline_image_position',
            field=models.IntegerField(default=0, null=True, verbose_name='Image Y-Axis Position'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='headline_image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, help_text='Please do NOT upload images that show a lot of blood, posing or other situations that may be offensive to people that are not familiar with hunting!\nA title pic will be displayed as background image on the trip page.', null=True, upload_to='trips/headline_images/', verbose_name='Title Image'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='staff_languages',
            field=jagdreisencheck.custom_fields.ListField(help_text='Please provide the staff languages at the hunting sight.', verbose_name='Staff Languages'),
        ),
    ]
