# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0035_ratingreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreply',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelling.Trip', verbose_name='Associated Trip'),
        ),
    ]
