# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0036_ratingreply_trip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingreply',
            options={'verbose_name': 'Rating Reply', 'verbose_name_plural': 'Rating Replies'},
        ),
        migrations.AlterField(
            model_name='ratingreply',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelling.Rating', unique=True, verbose_name='Associated Rating'),
        ),
    ]
