# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0037_auto_20190223_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingreply',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='travelling.Rating', verbose_name='Associated Rating'),
        ),
    ]
