# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0040_auto_20190224_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='marked_for_deletion',
            field=models.BooleanField(default=False, verbose_name='Marked for deletion'),
        ),
    ]
