# Generated by Django 2.1.7 on 2019-03-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0041_trip_marked_for_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='lead_inactive',
            field=models.BooleanField(default=True, verbose_name='Hunters may enquire this trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='lead_inactive_message',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Message to display when inquiries are disabled.'),
        ),
    ]
