# Generated by Django 2.1.7 on 2019-03-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0042_auto_20190319_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='lead_inactive',
            field=models.BooleanField(default=False, verbose_name='Hunters may enquire this trip'),
        ),
    ]
