# Generated by Django 2.1.7 on 2019-03-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0043_auto_20190319_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='hunters_experience',
            field=models.IntegerField(choices=[(1, 'Suitable for beginners (< 2 years experience)'), (2, 'Suitable for hunters with little experience (> 2 years & < 4 years)'), (3, 'Suitable for hunters with some experience (> 4 years & < 5 years)'), (4, 'Suitable for hunters with good experience (> 5 years & < 7 years)'), (5, 'Suitable for hunters with extensive experience (> 7 years)')], null=True, verbose_name='Suggested fitness'),
        ),
        migrations.AddField(
            model_name='trip',
            name='hunters_fitness',
            field=models.IntegerField(choices=[(1, 'No fitness required'), (2, 'Almost no fitness required'), (3, 'Some fitness required'), (4, 'Good fitness required'), (5, 'Strong fitness required')], null=True, verbose_name='Suggested fitness'),
        ),
    ]
