# Generated by Django 2.1.7 on 2019-03-25 11:17

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0044_auto_20190324_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='HunterDataInInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('budget', djmoney.models.fields.MoneyField(decimal_places=2, default=None, default_currency='EUR', max_digits=8, null=True, verbose_name='Budget')),
                ('license_since', models.IntegerField(null=True, verbose_name='Year the hunting license was obtained')),
                ('shooting_experience', models.IntegerField(null=True, verbose_name='Approx. Shooting experience')),
                ('physical_fitness', models.IntegerField(choices=[(1, 'No fitness'), (2, 'Almost no fitness'), (3, 'Some fitness'), (4, 'Good fitness'), (5, 'Strong fitness')], null=True, verbose_name='Physical Fitness')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
            ],
        ),
        migrations.RemoveField(
            model_name='travelinquiry',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='travelinquiry',
            name='budget_currency',
        ),
        migrations.RemoveField(
            model_name='travelinquiry',
            name='game',
        ),
        migrations.RemoveField(
            model_name='travelinquiry',
            name='kind_of_inquiry',
        ),
        migrations.AddField(
            model_name='travelinquiry',
            name='accommodation',
            field=models.CharField(choices=[('SO', 'Self Organized'), ('CA', 'Camping'), ('CO', 'Simple Cottage'), ('HH', 'Holiday Home / Hunting Chalet'), ('LO', 'Lodge'), ('HC', 'Hunting Chalet'), ('HO', 'Hotel')], max_length=2, null=True, verbose_name='Accommodation'),
        ),
        migrations.AddField(
            model_name='travelinquiry',
            name='hunting_type',
            field=models.CharField(choices=[('P', 'Stalking'), ('A', 'Stand Hunting'), ('G', 'Joint Hunting')], default='P', max_length=1, verbose_name='Primary Hunting Type'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hunters_experience',
            field=models.IntegerField(choices=[(1, 'Suitable for beginners (< 2 years experience)'), (2, 'Suitable for hunters with little experience (> 2 years & < 4 years)'), (3, 'Suitable for hunters with some experience (> 4 years & < 5 years)'), (4, 'Suitable for hunters with good experience (> 5 years & < 7 years)'), (5, 'Suitable for hunters with extensive experience (> 7 years)')], help_text='Please indicate the regularity hunters should hunt in order to be prepared for the trip.', null=True, verbose_name='Suggested hunting experience'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hunters_fitness',
            field=models.IntegerField(choices=[(1, 'No fitness'), (2, 'Almost no fitness'), (3, 'Some fitness'), (4, 'Good fitness'), (5, 'Strong fitness')], help_text='Please indicate the physical fitness a hunter should have to be prepared for the trip.', null=True, verbose_name='Suggested fitness'),
        ),
        migrations.AddField(
            model_name='hunterdataininquiry',
            name='associated_inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelling.TravelInquiry', verbose_name='Associated Inquiry'),
        ),
        migrations.AddField(
            model_name='hunterdataininquiry',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelling.Game', verbose_name='Primary Game to hunt'),
        ),
    ]
