# Generated by Django 2.1.7 on 2019-03-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0045_auto_20190325_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelinquiry',
            name='num_of_hunters',
        ),
        migrations.AlterField(
            model_name='hunterdataininquiry',
            name='shooting_experience',
            field=models.IntegerField(null=True, verbose_name='Max. Shooting distance'),
        ),
    ]
