# Generated by Django 2.1.7 on 2019-03-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0047_auto_20190325_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Phone'),
        ),
    ]
