# Generated by Django 2.1.7 on 2019-03-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0048_travelinquiry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='approval_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Trip has been approved'),
        ),
    ]
