# Generated by Django 2.1.7 on 2019-03-29 08:52

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0049_auto_20190327_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='maps_location',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='Google Geo Location'),
        ),
    ]
