# Generated by Django 2.1.7 on 2019-03-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0050_trip_maps_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='address',
            field=models.CharField(blank=True, help_text='The Address will NOT be displayed to users. It is just for creating a google map.', max_length=150, null=True, verbose_name='Exact Address'),
        ),
    ]
