# Generated by Django 2.1.7 on 2019-04-02 11:19

from django.db import migrations
import jagdreisencheck.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0051_trip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='available_hunting_types',
            field=jagdreisencheck.custom_fields.ListField(null=True, verbose_name='Hunting Types'),
        ),
    ]
