# Generated by Django 2.1.7 on 2019-04-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0052_auto_20190402_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Absolute URL'),
        ),
    ]
