# Generated by Django 2.1.8 on 2019-04-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0053_auto_20190404_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['name'], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='reviewed_by',
        ),
    ]
