# Generated by Django 2.1.8 on 2019-04-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0054_auto_20190416_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='lead_inactive',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='lead_inactive_message',
        ),
        migrations.AddField(
            model_name='trip',
            name='lead_status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Permanently inactive'), (2, 'Capacity limit reached for this season')], default=1, verbose_name='Lead Status'),
        ),
    ]
