# Generated by Django 2.1.8 on 2019-04-22 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0055_auto_20190418_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunterdataininquiry',
            name='physical_fitness',
            field=models.IntegerField(choices=[(1, 'less than 1km walking distance per day'), (2, 'between 1km and up to 2.5km walking distance per day'), (3, 'between 2.5km and up to 5km walking distance per day'), (4, 'between 5km and up to 10km walking distance per day'), (5, 'more than 10km walking distance per day')], null=True, verbose_name='Physical Fitness'),
        ),
        migrations.AlterField(
            model_name='ratingreply',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='travelling.Rating', verbose_name='Associated Rating'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hunters_fitness',
            field=models.IntegerField(choices=[(1, 'less than 1km walking distance per day'), (2, 'between 1km and up to 2.5km walking distance per day'), (3, 'between 2.5km and up to 5km walking distance per day'), (4, 'between 5km and up to 10km walking distance per day'), (5, 'more than 10km walking distance per day')], help_text='Please indicate the average walking distance per hunting day.', null=True, verbose_name='Suggested fitness'),
        ),
    ]
