# Generated by Django 2.1.8 on 2019-04-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0056_auto_20190422_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingreply',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratingreply', to='travelling.Rating', verbose_name='Associated Rating'),
        ),
    ]
