# Generated by Django 2.0.13 on 2019-05-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0057_auto_20190422_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='Detailed Trip Description'),
        ),
    ]
