# Generated by Django 2.0.13 on 2019-06-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0058_auto_20190521_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accommodationprice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='accommodationprice',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='accommodationpricelist',
            name='pricelist_ptr',
        ),
        migrations.AlterUniqueTogether(
            name='gameprice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gameprice',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameprice',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='gamepricelist',
            name='pricelist_ptr',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccommodationPrice',
        ),
        migrations.DeleteModel(
            name='AccommodationPriceList',
        ),
        migrations.DeleteModel(
            name='GamePrice',
        ),
        migrations.DeleteModel(
            name='GamePriceList',
        ),
        migrations.DeleteModel(
            name='PriceList',
        ),
    ]
