# Generated by Django 2.0.13 on 2019-07-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0059_auto_20190611_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='airport_transfer',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Unknown')], default=2, null=True, verbose_name='Airport Transfer'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='alternative_activities',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Unknown')], default=2, help_text='Is there an oportunity to spend time besides hunting activities?', null=True, verbose_name='Alternative Offers'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='broadband_internet',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Unknown')], default=2, help_text='Please indicate if hunters can access the internet via WiFi.', null=True, verbose_name='Broadband Internet'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='family_offers',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Unknown')], default=2, null=True, verbose_name='Family Offers'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='interpreter_at_site',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Unknown')], default=2, help_text='Please indicate if there is an interpreting service at the hunting sight.', null=True, verbose_name='Interpreting Service'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='rifle_rentals',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Unknown')], default=2, null=True, verbose_name='Rifle Rentals'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='wireless_coverage',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes'), (2, 'Unknown')], default=2, help_text='Please indicate if hunters have mobile network access at your property.', null=True, verbose_name='Wireless Coverage'),
        ),
    ]
