# Generated by Django 2.0.13 on 2019-09-29 20:43

from django.db import migrations
import jagdreisencheck.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0060_auto_20190708_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='available_hunting_types',
            field=jagdreisencheck.custom_fields.ListField(default='["P"]', null=True, verbose_name='Hunting Types'),
        ),
    ]
