# Generated by Django 2.0.13 on 2019-11-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0061_auto_20190929_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='accommodation_rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Rather Bad'), (3, 'Neutral'), (4, 'Rather Good'), (5, 'Good')], help_text='Please rate the accommodation you had during your stay. Even a camping sight may get 5 stars if everything was fine.', null=True, verbose_name='Accommodation Rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='meal_quality',
            field=models.IntegerField(blank=True, choices=[(1, 'Bad'), (2, 'Rather Bad'), (3, 'Neutral'), (4, 'Rather Good'), (5, 'Good')], null=True, verbose_name='Catering Quality'),
        ),
    ]
