# Generated by Django 2.0.13 on 2020-02-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0063_auto_20200226_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Review Dislikes'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Review Likes'),
        ),
    ]
