# Generated by Django 2.0.13 on 2020-03-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelling', '0064_auto_20200226_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
